name: Push Docker Image to GitHub Container Registry

on:
  workflow_dispatch:
    inputs:
      source_image:
        description: 'Source Docker image to push'
        required: true
        default: 'bharanidharan/galaxykick:v100'
      destination_image:
        description: 'Destination image name in GHCR'
        required: true
        default: 'galaxykick'
      destination_tag:
        description: 'Destination image tag in GHCR'
        required: true
        default: 'v100'

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull existing image from Docker Hub
        run: docker pull ${{ github.event.inputs.source_image }}

      - name: Convert repository owner to lowercase
        id: lowercase
        run: |
          echo "repo_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "dest_image=$(echo ${{ github.event.inputs.destination_image }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Tag image for GitHub Container Registry
        run: docker tag ${{ github.event.inputs.source_image }} ghcr.io/${{ steps.lowercase.outputs.repo_owner }}/${{ steps.lowercase.outputs.dest_image }}:${{ github.event.inputs.destination_tag }}

      - name: Push to GitHub Container Registry
        run: docker push ghcr.io/${{ steps.lowercase.outputs.repo_owner }}/${{ steps.lowercase.outputs.dest_image }}:${{ github.event.inputs.destination_tag }}

      - name: Tag and push latest if pushing main version
        if: ${{ github.event.inputs.destination_tag == 'v100' }}
        run: |
          docker tag ${{ github.event.inputs.source_image }} ghcr.io/${{ steps.lowercase.outputs.repo_owner }}/${{ steps.lowercase.outputs.dest_image }}:latest
          docker push ghcr.io/${{ steps.lowercase.outputs.repo_owner }}/${{ steps.lowercase.outputs.dest_image }}:latest
